### ISSUE TITLE
Naming conflict if installed at /usr/local/bin

### ISSUE THREAD

**Issue by eli-oat** [llimllib/gpt-bash-cli#1]
There already exists a utility on macOS called `gpt`, `gpt – GUID partition table maintenance utility`. Not a big problem, but perhaps worth flagging in the README if folks are installing to `/usr/local/bin` the other `gpt` will take precedence.

**Comment by llimllib** [comment]
Blugh! bogus.

(temp fix: you can put /usr/local/bin ahead of /usr/sbin in your PATH and this `gpt` will take precedence, PATH works by choosing a binary from whatever directory has that file first)

**Comment by llimllib** [comment]
I added a note [to the README](https://github.com/llimllib/gpt-bash-cli/tree/57d92f09aac690b25e6440d0cbd426e14f20fdc4#installation), thanks for the issue
