### ISSUE TITLE
"mktemp: too few X's in template"

### ISSUE THREAD

**Issue by rjpcasalino** [llimllib/gpt-bash-cli#8]
I ran into this error with the recent updates. Easy enough to fix but was confused and had to Google. I wonder if linux and macOS `mktemp` behave differently? Seems likely. In any case, thought I'd open an issue. Thanks for this tool, Bill! Very useful.

**Comment by llimllib** [comment]
What was the fix? Sorry I don't test on linux

**Comment by llimllib** [comment]
thanks for the report, let me know if https://github.com/llimllib/gpt-bash-cli/commit/587b790d90b671876a8d9d08848c2370e87dd84b is a sensible fix

**Comment by rjpcasalino** [comment]
That was it! Next time I'll throw up a PR. Thanks again
